### ISSUE TITLE
Inflections give only one form

### ISSUE THREAD

**Issue by soshial** [LUMII-AILab/Tezaurs#1]
For example [vēlēt](http://api.tezaurs.lv/v1/inflections/vēlēt) might have 2 different conjugations, but only 1 is given in the result.

**Comment by lauma** [comment]
To get desired forms you have to pass the inflectional paradigm (given in the entries.txt) as argument for the inflection service. In case of vēlēt it is either 16 or 17. To get both tables you have to make to service calls.

When no paradigm is given, inflection service just gives one variant form lexicon (which is smaller than the whole Tezaurs) or some guess if nothing is found in lexicon. So whenever possible, do use the paradigms given.

**Comment by soshial** [comment]
If the system is supposed to give only one answer, then why are there 2 nested lists?
```
[
    [
        {"Laiks":"Nepiemīt", ... }
    ]
]
```

**Comment by lauma** [comment]
@PeterisP , do you have any comments on this?

**Comment by soshial** [comment]
It surprises me, how taking several stems/conjugation number (already existing in the dictionary) could be more than 5 lines of code added to the API system :) I am sorry if I sound demanding, I just want to have reasonable server answers for Latvian <3

**Comment by lauma** [comment]
As I already said there https://github.com/LUMII-AILab/Tezaurs/issues/2#issuecomment-287608059, those are two differend systems. Tezaurs is tuned to be able to work with inflection service, but other direction is continuous work in progress.

Inflectional service is ment to be able to give at least some guess about forms even if one pases something completely out of vocabulary, e.g., pokemonizēt. This is kind of in contradiction with the request to give everything what is in Tēzaurs and only what is in Tēzaurs.
