### ISSUE TITLE
Not all forms present

### ISSUE THREAD

**Issue by soshial** [LUMII-AILab/Tezaurs#3]
Let's take a simple [darīt](http://api.tezaurs.lv/v1/inflections/dar%C4%ABt) example of conjugation. For some reason these forms were absent:
1. darījušā (def. participle past. of NOM and VOC fem. sg.)

**Comment by PeterisP** [comment]
The fem.sg.definite participle form is 'darījusī'.
http://api.tezaurs.lv:8182/inflect/json/en/dar%C4%ABt?guess=false
{"Tense":"Past","Mood":"Participle","Number":"Singular","Definiteness":"Definite","Gender":"Feminine","Wordform":"darījusī","Voice":"Active","Part of speech":"Verb","Case":"Nominative"},
